### ISSUE TITLE
Plugin couldn't be installed...

### ISSUE THREAD

**Issue by chimcen** [larsjuhw/OctoPrint-ExtraFileInfo#1]
When try to install you plugin i got the following error message during the installation:

`ERROR: Could not find a version that satisfies the requirement OctoPrint-SlicerSettingsParser (from OctoPrint-ExtraFileInfo==1.0.0) (from versions: none)
ERROR: No matching distribution found for OctoPrint-SlicerSettingsParser (from OctoPrint-ExtraFileInfo==1.0.0)
Fehler!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output`

Do you have any idea?

**Comment by Sekisback** [comment]
Uses [Octoprint-SlicerSettingsParser-Python3](https://github.com/Rob4226/OctoPrint-SlicerSettingsParser-Python3) to get the data.

you have to install the SlicerSettingsParser before

**Comment by larsjuhw** [comment]
Yes, this plugin uses a fork of SlicerSettingsParser but I did not specify that in the setup.py. Should be fixed now.
Hopefully the abandoned SlicerSettingsParser on the plugin repo will be updated someday.
