### ISSUE TITLE
No details in file list

### ISSUE THREAD

**Issue by sleake** [larsjuhw/OctoPrint-ExtraFileInfo#12]
Setting things up as outlined, I am able to see the additional information in the active print section, but nothing shows in the file list. I am using Slicer Thumbnails but from the notes for ExtraFileInfo, it sounds like it should work fine. What else do I need to look at?

Infill Density and Top Layers are the two I used just to see if it works.
<img width="337" alt="Screen Shot 2022-12-04 at 7 11 09 PM" src="https://user-images.githubusercontent.com/4959070/205524695-b4967eb1-a3fe-4f5f-b96c-5f53ae89f99c.png">

**Comment by larsjuhw** [comment]
That is very strange. Are you sure that you selected the "Show in File info" checkboxes as well in the settings? Are any errors popping up in your browser console?

For more info, could you perhaps provide the gcode file and your ExtraFileInfo settings? You can find the settings in OctoPrint's config.yaml or by running `OctoPrint.settings.getPluginSettings("extrafileinfo").done(console.log);` in your browser console.

**Comment by sleake** [comment]
I'm known to be a bit strange, so I'm not surprised. :) 

<img width="575" alt="Screen Shot 2022-12-08 at 1 55 36 PM" src="https://user-images.githubusercontent.com/4959070/206544724-a794d4d2-d4d8-44c3-8091-874dddf66786.png">


<img width="515" alt="Screen Shot 2022-12-08 at 2 02 15 PM" src="https://user-images.githubusercontent.com/4959070/206544820-cd2617b5-1018-49ea-8c34-044bd520773d.png">

I tried another file just to verify, same thing:
<img width="472" alt="Screen Shot 2022-12-08 at 2 13 36 PM" src="https://user-images.githubusercontent.com/4959070/206546463-e4da7d40-33f8-4817-89a3-70af45f23e6d.png">


The source gcode file [Gcode file.zip](https://github.com/larsjuhw/OctoPrint-ExtraFileInfo/files/10188711/Gcode.file.zip)


If I go into the settings and uncheck the Active Print Info box, I can immediately see a change in that section. Then I check it back and it shows up again. Checking and unchecking File Info doesn't do anything.

In case it is a conflict with another plug in, here is my list of plug ins:
<img width="161" alt="Screen Shot 2022-12-08 at 2 10 15 PM" src="https://user-images.githubusercontent.com/4959070/206545916-9df788cb-3600-46bb-9ec6-6be2ace736f1.png">

**Comment by sleake** [comment]
I have been using Chrome so I tried Safari. Same issue.

Just to check things, I installed on another Octoprint instance I have for a different printer. This time I don't get anything in either location. Tried this on both browsers as well.

**Comment by larsjuhw** [comment]
Seems like TP-Link Smartplug causes this issue. That plugin [also hooks](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/blob/c69a0ee89a239d9b44f5d48572bcba9ea165131c/octoprint_tplinksmartplug/static/js/tplinksmartplug.js#L15) the function that returns the file information. It probably loads after ExtraFileInfo and overrides this plugin's hook.

**Comment by sleake** [comment]
That's interesting (why would a smart plug switching plugin have anything to do with the file info?) and a little funny. Unrelated to this, I installed PSU Control/PSU TP-Link to use with OctoDash and since my last post and I uninstalled TP-Link Smartplug. I had no idea it would be related so I didn't check the extra info. I just tried it and it works now:

<img width="676" alt="Screen Shot 2022-12-08 at 4 45 52 PM" src="https://user-images.githubusercontent.com/4959070/206574514-b94fcb9e-ad86-4d80-861a-dfbfb285fb04.png">


On a bit of a tangent, and not an issue, but a question/request:  Is it possible to put a short horizontal line in the file list between "Last print time" and when the extra info listing starts? It would make it stand out a little and quicker to visually scan to the start of the list. Not a full width line as that might be confusing in the file list section but just long enough to be a visual divider.

```
...
Estimated print time: 999999
Last Printed: 1/1/11
Last Print time: 99:99
------------------------------
Infill Density = 10%
Top Layers = 3
etc

```

Many thanks for your quick responses and resolution.  And thanks for creating this. As you may have seen, I have a bunch of those values in my files because I am forever forgetting what settings I used. It will be nice to see the key ones in Octoprint now instead of having to open the files.

**Comment by larsjuhw** [comment]
I will add that in the next version, probably with a toggle. Thanks for the suggestion.
The TP-Link plugin uses the file info view to display the electricity that the gcode file used last print.

**Comment by sleake** [comment]
Sounds good. Thanks again for the help/support.

**Comment by larsjuhw** [comment]
> On a bit of a tangent, and not an issue, but a question/request: Is it possible to put a short horizontal line in the file list between "Last print time" and when the extra info listing starts? It would make it stand out a little and quicker to visually scan to the start of the list. Not a full width line as that might be confusing in the file list section but just long enough to be a visual divider.
> 
> ```
> ...
> Estimated print time: 999999
> Last Printed: 1/1/11
> Last Print time: 99:99
> ------------------------------
> Infill Density = 10%
> Top Layers = 3
> etc
> ```
@sleake I've added this in 1.4.0rc1. However I hadn't configured the RC release channel in previous versions, so you'll need to manually install the zip by installing this url from OctoPrint's plugin install window: https://github.com/larsjuhw/OctoPrint-ExtraFileInfo/archive/refs/tags/1.4.0rc1.zip

You will still automatically receive future releases after a manual install. Please let me know if you like it or have any issues!
