### ISSUE TITLE
Feature Request: Conditional Display

### ISSUE THREAD

**Issue by codefaux** [larsjuhw/OctoPrint-ExtraFileInfo#13]
Hey there! I've been using this for ages, and I was doing some cleanup and realized I'd love an extra feature.

I'd like some items to only show sometimes. 

For example, `; ironing = 0` -- I'd prefer to only see that when it's enabled. Same with `; spiral_vase = 0` and `; fuzzy_skin = none` and similar. That way, I can identify "specialized" prints, without having to clutter up **all** of my prints.

For implementation, it seems logical to use either `Only show if not Zero/Empty` as a checkbox, or `Only show if not matching` as a text box, optionally with a Regex matcher.

**Comment by larsjuhw** [comment]
Good idea! When I can find some time I'll look into it. Currently very busy with school however.

**Comment by larsjuhw** [comment]
@codefaux Almost a year later.. but I finally got back into 3D printing and found some time to update this plugin and add an option to input a custom Jinja template (which required an entire rewrite of the plugin). If you're still using this plugin then you can test it by installing release candidate 2.0.0rc1, by installing this url: https://github.com/larsjuhw/OctoPrint-ExtraFileInfo/archive/refs/tags/2.0.0rc1.zip

You can make a custom Jinja template and use if-statements to achieve this. Check the [README on the rc branch](https://github.com/larsjuhw/OctoPrint-ExtraFileInfo/tree/rc#custom-jinja-template) for a brief explanation, or look at the [default Jinja template](https://github.com/larsjuhw/OctoPrint-ExtraFileInfo/blob/rc/octoprint_extrafileinfo/templates/extrafileinfo_additionalInfo.jinja2) for reference.

**Comment by codefaux** [comment]
Hey, congrats on getting back at it. I'm sorry to say, I'm no longer using OctoPrint -- my printer uses Klipper, so I've moved to Mainsail. It's a real shame because I still want this sort of plugin/feature, now moreso than before, lol.

Awesome work on getting an RC up. It looks like it would do precisely what I wanted/suggested. Sorry I can't help iron it out.

**Comment by larsjuhw** [comment]
No worries! I’ve personally moved to Klipper as well.
