### ISSUE TITLE
Great idea!  Would it be possible to add a few examples? The issue is I’m not so good at finding them

### ISSUE THREAD

**Issue by Zakoplex** [larsjuhw/OctoPrint-ExtraFileInfo#2]
Would it be possible to include a few examples of common key label value sets? This is a great idea! Thanks!

**Comment by larsjuhw** [comment]
I added an example and more information about SlicerSettingsParser to the README. The keys entirely depend on which slicer you use and how it is setup. Read [this](https://github.com/larsjuhw/OctoPrint-ExtraFileInfo#slicersettingsparser) for more explanation.

**Comment by Zakoplex** [comment]
Thank you!
