### ISSUE TITLE
Unable to update to 1.2.0

### ISSUE THREAD

**Issue by edekeijzer** [larsjuhw/OctoPrint-ExtraFileInfo#7]
When I tried to update your plugin to the most recent version, I got an error from Octoprint that the downloaded file of 105 bytes is not a zipfile. Retrieved [the url](https://github.com/larsjuhw/OctoPrint-Extrafileinfo/archive/1.2.0.zip) from the error message and when I try to download this manually I get the following:
```the given path has multiple possibilities: #<Git::Ref:0x00007f6413b0dde8>, #<Git::Ref:0x00007f6413b0dac8>```
A little research pointed out that this is most likely caused by you having both a release as well as a branch with the same name.

**Comment by edekeijzer** [comment]
Workaround to still get the update is to manually install the [zipfile from the master branch](https://github.com/larsjuhw/OctoPrint-ExtraFileInfo/archive/refs/heads/master.zip)

**Comment by ackerthehacker2** [comment]
How do you manually install it?
